# Diseños de Nivel
# Ajustado para main_map.png con MAYOR PRECISIÓN (16px grid)
# Altura 720px / 16px = 45 filas
# Ancho 5248px / 16px = 328 columnas

# P = Player
# E = Enemy
# X = Pared/Plataforma

# Generamos un mapa base largo
row_empty = " " * 328
row_floor = "X" * 328

level_0 = [
    row_empty,
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                                                                                                                                                                                                ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                                                                                                                                                                                                ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                                                                                                                                                                                                ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                                                                                                                                                                                                ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                                                                                                                                                                                                ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                                                                                                                                                                                                ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                                                                                                                                                                                                ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                                                                                                                                                                                                ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                     XXXXXXXXXXXX                                                                                                                                                               ",
    "XXXXXX                                 E                                    XXXXXXXXXXXX                                                                     XXXXXXXXXXXX                                                                                                                                                               ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                     XXXXXXXXXXXX                                                                                                                                                               ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                     XXXXXXXXXXXX                                                                                                                                                               ",
    "XXXXXX                                                                      XXXXXXXXXXXX                                                                     XXXXXXXXXXXX                                                                                                                                                               ",
    "XX                          XXXXXXXXXXXXXXXXXXXXXXXXX                          XXXXX                                                                            XXXXXX                                                                                                                                                                  ",
    "XX                          XXXXXXXXXXXXXXXXXXXXXXXXX                          XXXXX                                                                            XXXXXX                                                                                                                                                                  ",
    "XX                                                                             XXXXX                                                                            XXXXXX                                                                                                                                                                  ",
    "XX                                                                             XXXXX                                                                            XXXXXX                                                                                                                                                                  ",
    "XX                                                                                                                                                              XXXXXX                                                                                                                                                                  ",
    "XX                                                                                                                                                                                                                                                                                                                                      ",
    "XX              XXXXXXX                                                                                                                                                                                                                                                                                                                 ",
    "XX              XXXXXXX                                                                                                                                                                                                                                                                                                                 ",
    "XX                                                                                                                                                                                                                                                                                                                                      ",
    "XX                                                                                                                                                                                                                                                                                                                                      ",
    "XX                                                                                                                                                                                                                                                                                                                                      ",
    "XX                                                                                                                                                                                                                                                                                                                                      ",
    "XX                                                                            XXXXXX                                                                            XXXXXX                                                                                                                                                                  ",
    "XX                                                                            XXXXXX                                                                            XXXXXX                                                                           B XXXXXX                                                                                ",
    "XXXXXXXXXXXX                                                         XXXXXXXXXXX  XXXXXXXXXXXX                      XXXXXXXXXX                    XXXXXXXXXXXXXXXX  XXXXXX                                                                   XXXXXX                                                                                     ",
    "XXXXXXXXXXXX                                                         XXXXXXXXXXX  XXXXXXXXXXXX                      XXXXXXXXXX                    XXXXXXXXXXXXXXXX  XXXXXX           E                                                        XXXXXX                                                                                     ",
    "      XX                                                                                                                                    XXXXXX                                                          P                                XX                                                                                         ",
    "      XX                                                                                                                                    XXXXXX                                                                                           XX                                                                                         ",
    "      XX        XXXXXXXXXXXX                                                                  XXXXXXXXXXXXXXXX                    XXXXXXXXXX                              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                             XX                                                                                         ",
    "      XX        XXXXXXXXXXXX                                                                  XXXXXXXXXXXXXXXX                    XXXXXXXXXX                              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                             XX                                                                                         ",
    "      XX                            XXXXXXXXXXXX                                                                                                                                                                                             XX                                                                                         ",
    "      XX                            XXXXXXXXXXXX                                                                                                                                                                                             XX                                                                                         ",
    "      XX                                                                                                                                                                                                                                     XX                                                                                         ",
    "      XX                                                                                                                                                                                                                                     XX                                                                                         ",
    "      XX                                                 XXXXXXXXX                                                                                                                                                                           XX                                                                                         ",
    "      XX                                                 XXXXXXXXX                                                                                                                                                                           XX                                                                                         ",
    "      XX                                                                                                                                                                                                                                     XX                                                                                         ",
    "      XX                                                                                                                                                                                                                                     XX                                                                                         ",
    "      XX                                                                                                                                                                                                                                     XX                                                                                         ",
    "      XX                                                                                                                                                                                                                                     XX                                                                                         ",
    row_floor,
    row_floor,
]

levels = [level_0]
